### ISSUE TITLE
Tag author date references and format references.yml entries

### ISSUE THREAD

**Issue by geealbers** [thegetty/egypt-classical-world#14]
Instructions follow. I did an initial test for essay 1 in the `add-author-date` branch, which you can just take over and work in for the remaining essays.

## Essays

For each essay, run a regex find and replace with the patterns below. This will wrap the author date reference in a single set of curly brakckes, which we can then use to go back and turn into shortcodes with a single global command. It will catch standard uses like "Bachhuber 2006"; entries with "et al.", like "Kuniholm et al. 1996"; and entries with a and b years, like "Emanuel 2014a" and "Emanuel 2014b". However, it will not work for multiple name entries, like; "Aruz, Benzel, and Evans 2008"; or for hyphenated names or dates like "Suchowska-Ducke 2015" or "Whitley et al. 2005–6". So, you need to go through one at a time and either do the auto-replace by clicking the Replace button if the pattern caught the full reference, or manually highlight the full reference and add the curly brackets that way.

**Find:**

```
([A-Z][a-z]+?[ et al\.]* [0-9]{4}[a-x]*)
```

**Replace:**

```
{$1}
```

## References YAML

For each bibliography file, delete the "References Cited" heading and leave two line breaks at the top of the file. Run a regex find and replace using the pattern below, but update number in `essay: 1` to reflect the actual essay number. Copy and paste the results into references.yml, and make sure it's all indented in properly. 

**Find:**

```
\n\n(.+)?
```

**Replace:**

```
- id: ""
  essay: 1
  full: "$1"\n
```

Next, manually go through the references and create the appropriate `id` text. These `id`s will ultimately match those surrounded in curly brackets in the essays. So if you're not sure of the formatting, you can do a search in the essay itself to see how the editors formatted it. A couple examples:

```yaml
- id: "Abbas 2017"
  essay: 1
  full: "Abbas, Mohamed Raafat. 2017. “A Survey of the Military Role of the Sherden Warriors in the Egyptian Army during the Ramesside Period.” *Égypte Nilotique et Méditerranéenne* 10:7–23."
- id: "Aruz, Benzel, and Evans 2008"
  essay: 1
  full: "Aruz, Joan, Kim Benzel, and Jean M. Evans, eds. 2008. *Beyond Babylon: Art, Trade, and Diplomacy in the Second Millennium B.C*. New York: Metropolitan Museum of Art."
- id: "Manning et al. 2001"
  essay: 1
  full: "Manning, Sturt W., et al. 2001. “Anatolian Tree Rings and a New Chronology for the East Mediterranean Bronze-Iron Ages.” *Science* 294, no. 5551 (December 21): 2532–35."
- id: "Waal"
  essay: 1
  full: "Waal, W. J. I. Forthcoming. “Distorted Reflections? Writing the Late Bronze Age in the Mirror of Anatolia.” In *Linguistic and Cultural Interactions between Greece and the Ancient Near East: In Search of the Golden Fleece*, edited by Michele Bianconi. Leiden: Brill."
```
